const tabFieldsMap = {
  general: [
    "name",
    "slug",
    "category",
    "category_desc",
    "tagline",
    "short_code",
    "youtube_link",
    "night",
    "original_price_usd",
    "discounted_price_usd",
  ],
  description: ["short_description", "description"],
  location: ["latitude", "longitude", "location", "region", "how_to_get"],
  faqs: ["faqs"],
  hosts: ["hosts"],
  highlights: ["highlights"],
  overview: ["overview"],
  itinerary: ["itinerary"],
  dossiers: ["dossiers"],
  departure: ["departure"],
  files: [
    "files",
    "featuredImages",
    "galleryImages",
    "faqImages",
    "locationCover",
    "howToGet",
  ],
  other: [
    "amenity",
    "related_homestay",
    "related_experience",
    "related_circuit",
    "related_package",
    "nearby_homestay",
    "manager_id",
    "what_to_bring",
    "excluded",
  ],
};

export default tabFieldsMap;
